name: XalTools
version: '${version}'
main: me.serbob.xaltools.XalTools
api-version: '1.21'
folia-supported: true
softdepend:
  - "WorldGuard"
  - "Lands"
  - "DonutWorth"
  - "EconomyShopGUI"
  - "EconomyShopGUI-Premium"
  - "ShopGUIPlus"
  - "PrimeSeller"

commands:
  xaltools:
    description: kool plg

permissions:
  xaltools.admin:
    default: op
